git:
  depth: 5
jobs:
  include:
  - stage: Build And Test JAVA
    language: java
    jdk: oraclejdk11
    before_script:
    - cd sample-application-backend
    script:
    - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=drayanqi_sample-application-students

  - stage: Build and Test Nodejs
    language: node_js
    node_js: '12.20'
    before_script:
    - cd sample-application-frontend
    script:
    - echo "npm install ..."
    - npm run lint
    - npm install
    - npm run test

  - stage: Build and push Frontend Image
    before_script:
    - cd sample-application-backend
    script:
    - echo "Docker build ..."
    - docker build  -t $DOCKER_LOGIN/backend .
    - echo "Logging in to docker ... $DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
    - echo "docker push images..."
    - docker push $DOCKER_LOGIN/backend
  
  - stage: Build and push Backend Image
    before_script:
    - cd sample-application-backend
    - echo "Logging in to docker..."
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
    - docker build -t $DOCKER_LOGIN/frontend .
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm"
env:
  global:
  - secure: lee3w2kflXjAhUUIFaDyP8l5Z+1JL09xk2PSPKbIqTDeHVvwOGuJQmgHrwd29JZ36CKd+sVQ78iDAY55vemo23UYpMv11WjIywg7X6yqdgHlB4zbqSnVouXaDnkxCL+RCJzUdxM1M8hvNaqqa4HawwWKbcvlH6+aa1z2qPG4FmzC+K9pB6ooqstT8VwsB6E7BkO2NNf0LAO8Kg7vdRsA6cksQuY1vOgptrCf85NR38AyEqTSNvqmSBhGCEeRhEiL/eGDdNOVeymcBiBo5gUXP41JjFqcx3tSk6HFAd4V2dF/EJpb8nTnH6emukLAY0CpjgVYRJf3z1zX/KvLkyCERgDpj1//6YiKD6D6AeDft+E9fSBZpUU1dN3kqHUiEYmaU7k0/KOD/eeCtOg3KaoQc4HYJJB0zkAXTVso9MKdmPLdO17JzkX6WGRXps7tv8M7Ex+pjxJafWz6OuAVSYCvjV6QxKPMCaPqQ4mvZ2049BqT6e2UQd14te0GzwQWmE677LWVwCWWpTp79ZoTK71AjGFXat3626gR5QIrNfDKoIVUv7/Zn3e4seDksFPYKnxKEnmkJvirG5ScFBgd8SIaFH1XPAm29wAGAqbQoUkQQeiPFBrPVp+Jq0K1Xb6nKYhSlaj7LUFtCTaPK1WG3ZpNtpsKd19BJLTCFif2T/rG8+4=
  - secure: e3pubCM6cBPv8+mIw/0mcvWAjwq4SvV0DySXvCDSVPlPM8QXTr/CZADRIZzQ8BInRctkwNgSW9r2Bao1aHakvU8l7vQPPMUcGVdH9rbft03pBmOeStPacGeUntGct2ufnBoZBn5IqPJ27RoM7yNuehP5JT7cac3ikW4fM4/wH3L9iYoDmmTAV8N+ktTjNhMp+E2OEbflg/86afHqdpsSZDLatulrtR6mcOwwnVpVAAMeHzDMcN92BorYNLzW7alKXjEELXjtlcZ/CCVk0oc0zqqPbRBYZqF1s3ux9RBQ49R0D7vTg7o2Bkx4F2zc1wLmeXmWFm5tBhKf3p5xiQI6K8uncD4ZeXD7noEi57/v8CN6J5My03i74Pv1gt+1D04q6qT3nBXC8TFsqIF0b7xO/ODLw9Azb5CiUvKJxgjAR72Ce7vRVae88RIYpIru5iWCdN6SRwEvyyPOyinmmXP8V7BqVD/LA0oR6sYgtoxU73mf/HViWNYVrfhV9gw0XtciUmx4VQYY0ZBg4YUlyd/puxnZPjmtrkyu7+EiEMGMOoyUIHnFgPT/GKY1Hod3ZDx4M0ZbBMjHIgQM2BgOa6b5Js7tKH9zPJxTsdi197NKY/U8e0irnF/TVNmNNyoZmz5ruh3McL0X0AxF/KvFi8pDoQHh2jsGBMgMK6txf31rWUE=
    
services:
  - docker

addons:
  sonarcloud:
    organization: "drayanqi"
    token: "$SONARCLOUD_TOKEN"
