git:
  depth: 5
jobs:
  include:
    - stage: "Build and Test Java"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
      script : 
        - mvn clean verify
    - stage: "Build and Test Nodejs"
        language: node_js
        node_js: "12.20"
        before_script:
          - cd sample-application-frontend
        script:
          - npm run test
cache:
  directories:
    - 'D:\libs\apache-maven-3.6.3\apache-maven\src\bin'
    - 'D:\programs'